marketplace/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views, email, search

app_name = 'marketplace'
urlpatterns = [
    path('', views.IndexViews.as_view(), name='index'),
    path('addListing', views.ListingViews.as_view(), name = 'addListing'),
    path('profile', views.ProfileViews.as_view(),name = 'profile'),
    path('search', search.SearchViews.as_view(), name='search'),
    path('myListings', views.MyListings.as_view(), name='myListings'),
    path('Signout', views.Signout, name = 'Signout'),
    path('email/send', email.send_intro_message, name='send_intro'),
    path('email/receive', email.receive_message, name='receive_message'),
    path('item/<int:pk>', views.ItemDetail.as_view(), name='item_detail'),
    path('item/<int:pk>/conversation', email.ConversationView.as_view(), name='message_list'),
    path('updateListing/<int:pk>', views.UpdateListingView.as_view(), name='updateListing'),
    path('accounts/login/', views.login, name='login'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

textbookswap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('marketplace.urls', namespace='marketplace')),
    path('', include('social_django.urls', namespace='social')),
]

marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from phone_field import PhoneField
from django_auto_one_to_one import AutoOneToOneModel
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.urls import reverse
from django.core.validators import MinValueValidator
import uuid
import os
# Create your models here.

class Profile(AutoOneToOneModel(User)):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    imagefile = models.ImageField(upload_to='images/', null=True, blank=True)
    phonenumber = PhoneField(null=True, blank=True)
    major = models.CharField(max_length=50, null=True, blank=True)
    year = models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0)])

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'

@receiver(post_save, sender=User)
def ensure_profile_exists(sender, **kwargs):
    if kwargs.get('created', False):
        Profile.objects.get_or_create(user=kwargs.get('instance'))

# @receiver(models.signals.pre_save, sender=Profile)
# def auto_delete_file_on_change(sender, instance, **kwargs):
#     if not instance.pk:
#         return False

#     try:
#         old_file = sender.objects.get(pk=instance.pk).imagefile
#     except sender.DoesNotExist:
#         return False

#     new_file = instance.imagefile
#     if not old_file == new_file:
#         if not old_file.name == '' and os.path.isfile(old_file.path):
#             os.remove(old_file.path)


class Item(models.Model):
    item_condition_choices = (("Like New", "Like New"),("Good", "Good"), ("Fair", "Fair"), ("Poor", "Poor"))
    #Any changes to name, author, or description max_length will need to be refected in views.py's book API string value truncation
    item_name = models.CharField(max_length=300, null=True)
    item_isbn = models.CharField(max_length=100, null=True)
    item_edition = models.IntegerField(null=True, default = 1)
    item_author = models.CharField(max_length=100, null=True)
    item_course = models.CharField(max_length=100, null=True)
    item_price = models.IntegerField(null=True)
    item_image = models.ImageField(upload_to='images/', null=True)
    item_condition = models.CharField(max_length=20, choices=item_condition_choices, default= "Like New")
    item_posted_date = models.DateField(null=True)
    item_seller_name = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    item_description = models.TextField(max_length= 2000, null=True)
    item_status_choices = (("Available", "Available"),("Sold", "Sold"), ("Hidden", "Hidden"))
    item_status = models.CharField(max_length=20, choices=item_status_choices, default= "Available")


    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('marketplace:myListings')


class Conversation(models.Model):
    buyer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.buyer} interested in {self.item}'

class Message(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    in_response_to = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

marketplace/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
import re

from .models import Profile, Item
from . import models

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'email',
            'first_name',
            'last_name',
            'password',
        ]
class ImageForm(forms.ModelForm):
    class Meta:
        model= Profile
        fields= ["imagefile" ,"phonenumber", "major", "year"]

class ItemForm(forms.ModelForm):
    class Meta:
        model= Item
        fields= ["item_image"]


class EmailProfileField(forms.Field):
    '''extract email from "name <name@example.com>"'''
    def clean(self, value):
        email_re = re.compile(r'<(.+@.+\..+)>')
        email = email_re.search(value)
        if email is None:
            raise forms.ValidationError
        email = email.group(1)
        from_user = models.User.objects.filter(email=email)[0]
        return from_user.profile


class EmailUuidField(forms.Field):
    '''extract uuid from "name <name+uuid@example.com>"'''
    def clean(self, value):
        uuid_re = re.compile(r'\+(.*?)@')
        uuid = uuid_re.search(value)
        if uuid is None:
            raise forms.ValidationError
        uuid = uuid.group(1)
        in_response_to = models.Message.objects.get(pk=uuid)
        return in_response_to


class ReceiveMessageForm(forms.ModelForm):
    '''process emails from CloudMailIn'''
    author = EmailProfileField()
    in_response_to = EmailUuidField()
    conversation = forms.ModelChoiceField(
        queryset=models.Conversation.objects.all(),
        required=False)

    class Meta:
        model = models.Message
        fields = ['author', 'in_response_to', 'conversation', 'text']

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data['conversation'] = cleaned_data['in_response_to'].conversation
        return cleaned_data


class SendMessageForm(forms.Form):
    text = forms.CharField(strip=True,
                           error_messages={'required': "Type a message"},
                           label='')
    to = forms.ModelChoiceField(queryset=models.Profile.objects.all(),
        widget=forms.HiddenInput)
    conversation = forms.ModelChoiceField(
        queryset=models.Conversation.objects.all(),
        widget=forms.HiddenInput)
    in_response_to = forms.ModelChoiceField(queryset=models.Message.objects.all(),
        widget=forms.HiddenInput)

marketplace/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.utils import timezone
from django.contrib.auth.forms import UserChangeForm
from django.urls import reverse
from .forms import ImageForm, ItemForm
from .forms import EditProfileForm
from .models import Item, Profile
from django.shortcuts import get_object_or_404
from django.contrib import messages

import requests



# Create your views here.
class IndexViews(generic.ListView):
    template_name = "marketplace/main.html"
    context_object_name = "allItems"
    num_listings_display = 30

    def get_queryset(self):
        return Item.objects.filter(item_status="Available") \
            .order_by('-item_posted_date')[:self.num_listings_display]

class ListingViews(generic.DetailView):
    template_name = "marketplace/addListing.html"

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, self.template_name, {
                'error_message': 'Must be Logged In',
            })
        else:
            form1 = ItemForm()
            args = {'form1': form1}
            return render(request, self.template_name, args)

    def post(self,request):
            item_name= request.POST.get("item_name", "defaultName")
            #change title to uppercase
            item_isbn= request.POST.get("item_isbn", "defaultName")
            #remove '-' if it contains
            item_isbn = item_isbn.replace('-', '')
            item_edition= request.POST.get("item_edition", -1)
            item_author= request.POST.get("item_author", "defaultAuthor")
            item_course= request.POST.get("item_course", "defaultCourse").upper()
            item_price= request.POST.get("item_price", -1 )
            item_description= request.POST.get("item_description", "No description entered")
            item_posted_date = timezone.now()
            item_condition = request.POST.get("item_condition", "Like New")
            item_seller_name =  Profile.objects.get(user=request.user)
            item_status = request.POST.get("item_status", "Available")

            form1 = ItemForm(request.POST, request.FILES)
            args = {"form1": form1}

             #check if author and title has been set, if not fill using information returned by API
            info_from_api = requests.get('https://www.googleapis.com/books/v1/volumes?q=isbn:'+ item_isbn).json()
            
            if item_name == "defaultName":
                try:
                    item_name= info_from_api['items'][0]['volumeInfo']['title']
                    max_length = 300 #Match this value with models.py
                    item_name = item_name[:min(len(item_name), max_length)] 
                except:
                    messages.error(request, 'ISBN not found! Please submit using Title/Author')
                    return render(request, self.template_name,args)

            if item_author == "defaultAuthor":
                item_author = info_from_api['items'][0]['volumeInfo']['authors'][0]
                max_length = 100 #Match this value with models.py
                item_author = item_author[:min(len(item_author), max_length)] 

            if item_description == "" and item_isbn != "defaultName":
                item_description= info_from_api['items'][0]['volumeInfo']['description']
                max_length = 2000 #Match this value with models.py
                item_description = item_description[:min(len(item_description), max_length)] 

            
            if form1.is_valid():
                item = form1.save(commit = "false")
                item.item_isbn = item_isbn
                item.item_name = item_name
                item.item_edition = item_edition
                item.item_author = item_author
                item.item_course= item_course
                item.item_price= item_price
                item.item_description = item_description
                item.item_posted_date = item_posted_date
                item.item_condition = item_condition 
                item.item_seller_name = item_seller_name
                item.item_status = item_status
                item.save()
                messages.success(request, 'Your form was submitted successfully!')
            else:
                messages.error(request, 'ERROR! Your form could not be submitted.')

            return render(request, self.template_name, args)


class UpdateListingView(generic.UpdateView):
    model = Item
    template_name = 'marketplace/update_listing.html'
    fields = ['item_status']


class ProfileViews(generic.DetailView):
    template_name = "marketplace/profilePage.html"

    def get(self, request):
        Profiles = Profile.objects.all()
        form = ImageForm()
        return render(request, self.template_name, {
            'user': request.user, "form": form
    })

    def post(self, request):
        form = ImageForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
        else:
            form = ImageForm()
        args = {"form": form}
        return render(request, self.template_name, args)


class MyListings(generic.ListView):
    template_name = "marketplace/myListings.html"

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, self.template_name, {
                'error_message': 'Must be Logged In',
            })
        else:
            user = get_object_or_404(Profile, user=request.user)
            allItems = Item.objects.filter(item_seller_name=user)
            availableItems = Item.objects.filter(item_status="Available",item_seller_name=user )
            soldItems = Item.objects.filter(item_status="Sold", item_seller_name=user)
            hiddenItems = Item.objects.filter(item_status="Hidden", item_seller_name=user)
            return render(request, self.template_name, {
                'allItems': allItems,
                'availableItems': availableItems,
                'soldItems': soldItems,
                'hiddenItems': hiddenItems,
            })


class ItemDetail(generic.DetailView):
    model=Item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['user_has_buyer_conversation'] = context['object'].conversation_set.all().filter(buyer=self.request.user.profile).exists()
        return context


def Signout(request):
    logout(request)
    return redirect('/')

def login(request):
    login_page = reverse('social:begin', args=['google-oauth2'])
    if 'next' in request.GET:
        login_page += '?next=' + request.GET['next']
    return redirect(login_page)

marketplace/templates/marketplace/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

      <link rel="stylesheet" type="text/css" href="{% static 'marketplace/main.css' %}">

      <title>{% block title %}Textbook Swap{% endblock %}</title>
  </head>
  <body>
  <style>
    body{
      background-image:url("{% static 'marketplace/images/Black-wood-photoshop-pattern-for-website-background.jpg' %}")
    }
    </style>
    <nav class="navbar navbar-expand-md navbar-dark bg-steel sticky-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'marketplace:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
        <a class="nav-item nav-link" href="{% url 'marketplace:addListing' %}">Add Listing</a>
        <a class="nav-item nav-link" href="{% url 'marketplace:myListings' %}">My Listings</a>
        <a class="nav-item nav-link" href="{% url 'marketplace:profile' %}">My Profile</a>
          </div>
          <!-- Navbar Right Side -->
	  {% if hide_search_bar %}
	  {% else %}
	  <form action="{% url 'marketplace:search' %}" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
          </form>
	  {% endif %}
          {% if user.is_authenticated %}
	  <a class="nav-item nav-link" href="{% url 'marketplace:profile' %}" style="color:white;">
            Hello, {{user.first_name}}
          </a>
          <a class="nav-item nav-link btn btn-outline-light" href="{% url 'marketplace:Signout' %}">Sign Out</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url "social:begin" "google-oauth2" %}">
          <button class="btn btn-primary" type="submit">Sign In</button>
          </a>
          {% endif %}
        </div>
	  </div>
	</nav>
      
      <main role="main" class="container">
            {% block content %}{% endblock %}
      </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      <script src="{% static 'marketplace/readmore.js' %}"></script>
  </body>
</html>

marketplace/templates/marketplace/conversation_list.html
{% extends 'marketplace/base.html' %}

{% block content %}
<a href="{% url 'marketplace:item_detail' view.kwargs.pk %}">
  <button type="button" class="btn btn-info btn-lg" style="margin-top: 1em;">&larr; Back to item</button>
</a>
<h1 class="text-on-dark-background">{{ item.item_name }} listed for ${{ item.item_price }}</h1>
{% for c in conversation_list %}
  <div class="jumbotron">
  <h3>Conversation with {{ c.to }}</h3>
  {% for message in c.conversation.message_set.all %}
    <p>
    <b>{{ message.author.user.first_name }}</b>: {{ message.text|escape }}
    </p>
  {% endfor %}
  <p>
    <form action="{{ request.path }}" method="POST">
      {% csrf_token %}
      {{ c.form }}
      <input type="submit" value="send" class="btn btn-outline-primary">
    </form>
  </p>
  </div>
{% empty %}
	<div class="jumbotron">
		<div class="display-4">No conversations yet</div>
	</div>
{% endfor %}
{% endblock %}

marketplace/templates/marketplace/item_card.html
<div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
<a href="{% url 'marketplace:item_detail' items.pk %}">
  <div class="card-header text-white bg-success">
    {{item.item_name}}
  </div>
  <div class="card-body text-white">
    {% if item.item_image  %}
    <img src="{{ item.item_image.url }}" id="imgProfile" style="width: 100px; height: 100px" class= "img-thubmnail" align="middle"/>
    {% else %}
    <img src="static/marketplace/images/emptyTextbook.PNG" id="imgProfile" style="width: 100px; height: 100px" align="middle" class= "img-thubmnail"/>
    {% endif %}
    <br>
    
    <strong> <font color="#00b300">Author:</font> </strong>{{item.item_author}} <br>
    <strong><font color="#00b300">Course: </font></strong> {{item.item_course}}
    <br>
    <strong> <font color="#00b300">Edition: </font> </strong> {{item.item_edition}}
    <br>
    <style>
      #more{{ item.pk}}{display: none;}
    </style>
    <strong> <font color="#00b300">Info: </font> </strong> {% if item.item_description|length > 150 %} {{ item.item_description|slice:":150" }}<span id= "dots{{ item.pk }}">...</span><span id="more{{ item.pk }}">{{item.item_description|slice:"150:"}}</span>
    <br><a> <button onclick="viewMoreOrLess({{item.pk}})" class="btn btn-secondary btn-sm" id= "{{ item.pk }}" >Read more</button> </a>
    {%else%} {{item.item_description}} {%endif%}
    <br>
    <strong><font color="#00b300">Price: </font></strong>${{ item.item_price }}
    <br>
    <strong><font color="#00b300">Posted: </font></strong> {{ item.item_posted_date }}

    {% if item.item_seller_name.user.username == user.username %}
    <br>
    <a class="btn btn-outline-light btn-small" href="{% url 'marketplace:updateListing' item.pk %}">Update Status</a>
    {% endif %}
  </div>
</a>
</div>

marketplace/templates/marketplace/item_detail.html
{% extends 'marketplace/base.html' %}
{% load static %}

{% block content %}
<h1 class="text-white">{{ object.item_name }}</h1>
<div class="text-on-dark-background">
  <p>edition: {{ object.item_edition }}</p>
  <p>by {{ object.item_author }}</p>
  <p>
  {% if object.item_image  %}
    <img src="{{ object.item_image.url }}" id="imgProfile"  style="max-width:20%;" class="img-thubmnail"/>
  {% else %}
  <img src="{% static 'marketplace/images/emptyTextbook.PNG' %}" style="max-width:20%;" id="imgProfile"  class="img-thubmnail"/>
  {% endif %}
  </p>
  <p>${{ object.item_price }}</p>
  <p>{{ object.item_condition }} condition</p>
  <p>Posted {{ object.item_posted_date|date:"SHORT_DATE_FORMAT" }}
  by {{ object.item_seller_name }}</p>
  {% if object.item_course %}
  <p>Used for {{ object.item_course }}</p>
  {% endif %}
  <p>{{ object.item_description }}</p>
</div>
{% if object.item_seller_name.user == request.user %}
<br>
<a class="btn btn-outline-light btn-small" href="{% url 'marketplace:updateListing' object.pk %}">Update Status</a>
<br>
<br>
{%endif%}

{% if not user.is_authenticated %}
<form action="{% url 'marketplace:login' %}" class="form-inline my-2 my-lg-0">
  <input type="hidden" name="next" value="{{ request.path }}" />
  <input type="submit" class="btn btn-info btn-lg" value="Contact seller" />
</form>
{% elif request.user == object.item_seller_name.user or user_has_buyer_conversation %}
<a href="{% url 'marketplace:message_list' object.pk %}">
  <button type="button" class="btn btn-info btn-lg">View messages</button>
</a>
{% else %}
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#contact">Contact seller</button>
{% endif %}

<div id="contact" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <h3>Contact</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <form action="{% url 'marketplace:send_intro' %}" method='POST' class="form-inline my-2 my-lg-0">
          {% csrf_token %}
          <input type="hidden" name="item" value="{{ object.pk }}">
          <div class="container">
            <label for="text">
              Send {{ item.item_seller_name }} a message telling them you're interested in buying "{{ item.item_name }}" and when you're available to make the exchange!
            </label>
            <div class="row">
              <textarea style="width:100%;" id="text" name="message"></textarea>
            </div>
            <div class="row">
              <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">
                send message
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
  
{% endblock %}

marketplace/templates/marketplace/main.html
{% extends 'marketplace/base.html' %}
{% block content %}

<div class="container">
    <br>
    <br>
    <div class="card bg-dark text-white">
  <img class="card-img" src="https://s26162.pcdn.co/wp-content/uploads/2017/12/covercover.jpg" alt="Card image">
  <div class="card-img-overlay">
      <br>
      <br>
      <br>
    <h1 class="display-3 text-center font-weight-bold bg-dark text-white">Welcome to Textbook Swap</h1>
      <br>
      <br>
      <br>
      <br>
    <h2 class="card-text bg-dark text-white text-center"><i>The marketplace to buy/sell textbooks with fellow Wahoos!</i></h2>


  </div>
</div>
<h1 class="display-4 text-white">Recent Listings</h1>
<div class="container">
        <div class="row row-cols-1 row-cols-md-4">
        {% for items in allItems %}
		<div class="col mb-4">
		{% include 'marketplace/item_card.html' with item=items %}
		</div>
        {% endfor %}
        </div>
</div>

{% endblock content %}

marketplace/templates/marketplace/myListings.html
{% extends 'marketplace/base.html' %}
{% load static %}
{% block content %}
    <br>
    <br>
    <br>
    {% if error_message %}
        <p align='center' style="color:red;"><strong>{{ error_message }}</strong></p>
    {% else %}
<div class="row">
  <div class="col">
          <h1 class="display-4 text-white">Current Listings</h1>

        {% for items in availableItems %}
            {% if items.item_seller_name.user.username == user.username %}
	      {% include 'marketplace/item_card.html' with item=items %}
	    {%endif%}
        {% endfor %}
  </div>
  <div class="col">
              <h1 class="display-4 text-white">Sold Listings</h1>
        <br>
        <br>
        <br>

        {% for items in soldItems %}
          {% if items.item_seller_name.user.username == user.username %}
	    {% include 'marketplace/item_card.html' with item=items %}
          {%endif%}
        {% endfor %}

  </div>
  <div class="col">
    <h1 class="display-4 text-white">Hidden Listings</h1>
    {% for items in hiddenItems %}
      {% if items.item_seller_name.user.username == user.username %}
        {% include 'marketplace/item_card.html' with item=items %}
      {%endif%}
    {% endfor %}
  </div>
</div>
    {% endif %}
{% endblock content %}

marketplace/templates/marketplace/notification_email.html
{{ name }} just sent you a message about {{ item.item_name }}. Reply directly to this email to respond or <a href="https://textbookswapuva.herokuapp.com{% url 'marketplace:message_list' item.pk %}">respond online</a>.
<br/>
<br/>
--------------------
<br/>
<br/>
{{ message|safe }}

marketplace/templates/marketplace/search_results.html
{% extends 'marketplace/base.html' %}

{% block content %}
<h1 class="text-on-dark-background">Search results for "{{ query }}"</h1>
<div class="text-on-dark-background">
	sort by:
	<form action="{% url 'marketplace:search' %}" class="btn-group btn-group-toggle" data-toggle="buttons">
		<input type="hidden" name="query" value="{{ query }}">
		{% for option in sort_options %}
			<label class="btn btn-secondary {% if sort == option %}active{% endif %}">
				<input type="radio" name="sort" value="{{ option }}" onchange="this.form.submit()" id="{{ option }}" {% if sort == option %}checked{% endif %}>
					{{ option }}
			</label>
		{% endfor %}
	</form>
</div>
<div class="list-group">
	{% for item in page_obj.object_list %}
	<div class="card text-center">
		<a href="{% url 'marketplace:item_detail' item.pk %}">
  <div class="card-header bg-success text-white"> <strong> {{item.item_name}} </strong> </div>
  <div class="card-body bg-dark text-white">
    {% if item.item_image  %}
    	<img src="{{ item.item_image.url }}" id="imgProfile" style="width: 100px; height: 100px" class= "img-thubmnail"/>
    {% else %}
    	<img src="static/marketplace/images/emptyTextbook.PNG" id="imgProfile" style="width: 100px; height: 100px" class= "img-thubmnail"/>
    {% endif %}
	  <h5 class="card-title text-white"><font color="#00b300">Price: </font>${{item.item_price}}</h5>
	  <p class="card-text text-white"><font color="#00b300">Info: </font>{{item.item_description}}</p>
	  <font color="#00b300">Posted by: </font> {{item.item_seller_name}}
	  <br>
	  <font color="#00b300">Posted on: </font> {{ item.item_posted_date }}
  </div>
  <div class="card-footer text-white bg-dark">
	  <a href="{% url 'marketplace:item_detail' item.pk %}" class="btn btn-outline-success">Go to Listing</a>
  </div>
</div>
	<br>
	{% empty %}
	<div class="jumbotron">
		<div class="display-4">No results found</div>
	</div>
	{% endfor %}
</div>

<div class="row justify-content-around">
{% if page_obj.has_previous %}
<div class="col-4">
	<form action="{% url 'marketplace:search' %}">
		<input type="hidden" name="query" value="{{ query }}">
		<input type="hidden" name="sort" value="{{ sort }}">
		<input type="hidden" name="page" value="{{ previous_page }}">
		<input type="submit" value="&larr; previous page" class="btn btn-light">
	</form>
</div>
{% endif %}
{% if page_obj.has_next %}
<div class="col-4">
	<form action="{% url 'marketplace:search' %}">
		<input type="hidden" name="query" value="{{ query }}">
		<input type="hidden" name="sort" value="{{ sort }}">
		<input type="hidden" name="page" value="{{ next_page }}">
		<input type="submit" value="next page &rarr;" class="btn btn-light">
	</form>
</div>
{% endif %}
</div>
{% endblock %}

marketplace/templates/marketplace/update_listing.html
{% extends 'marketplace/base.html' %}
{% load static %}
{% block content %}
<br>
<br>
<div class="add-Form">
    <form enctype="multipart/form-data" action="" method="post">
    {% csrf_token %}
    {{ form1.as_p }}
<div class="card">
  <div class="card-body text-center bg-secondary">
    <h1 class="card-title text-white">Update Status:</h1>
              <label class="text-white" for="item_status"><b>Status: </b></label>
              <select id="item_status" name="item_status">
                  <option value="Available">Available</option>
                  <option value="Sold">Sold</option>
                  <option value="Hidden">Hidden</option>
              </select>
              <br>
              <br>
          <button type="submit" class="btn btn-success btn-lg">Update</button>
        </form>

</div>
  </div>
</div>

{% endblock content%}